---
title: "Visualizing movement range during the COVID-19 pandemic"
date: "5/1/2022"
output: html_document
runtime: shiny
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
library(dplyr)
library(stringr)
library(shiny)
library(leaflet)
library(rgdal)

```

```{r Data for movement range maps}
## Importing usa dataframe
usa <- read.csv("movement_range_data_usa_2020.txt", sep = ",")

# selecting years of interest
usa_2020 <- usa %>%
  filter(year == 2020)

## Establishing the base map
nation_shp <- readOGR("cb_2021_us_nation_5m/cb_2021_us_nation_5m.shp",
                      verbose = FALSE)
county_shp <- readOGR("cb_2021_us_county_500k/cb_2021_us_county_500k.shp",
                      verbose = FALSE)
state_shp <- readOGR("cb_2021_us_state_500k/cb_2021_us_state_500k.shp",
                     verbose = FALSE)

usa_base <- leaflet() %>%
  addProviderTiles("CartoDB", 
                   options = providerTileOptions(minZoom = 4)) %>%
  setView(lng = -98.35, lat = 39.5, zoom = 4) %>%
  setMaxBounds(lng1 = -66.9513812, lat1 = 49.3457868,
               lng2 = -124.7844079, lat2 = 24.7433195) %>%
  addPolygons(data = nation_shp,
              color = "#6e7f80", 
              weight = 2) %>%
  addPolygons(data = state_shp,
              weight = 1,
              color = "#6e7f80",
              label = state_shp$NAME,
              group = "State",
              highlightOptions = highlightOptions(color = "black", 
                                                  weight = 3)) %>%
  addLayersControl(overlayGroups = c("State", "County"))

usa_county <- usa_base %>% 
  addPolygons(data = county_shp,
              weight = 1,
              color = "#6e7f80",
              label = county_shp$NAME,
              group = "County",
              highlightOptions = highlightOptions(color = "black", 
                                                  weight = 3))

## Building interactive page
ui <- fluidPage(
  
  # App title ----
  titlePanel("Movement Range Maps during the COVID-19 pandemic"),
    
    # Main panel for displaying outputs ----
    mainPanel(width = 8,
      
      # Output 1: National map of state averages ----
      
      h2("State daily averages of population movement"),
      p("We average over state to visualize changes on a national level over the course of the COVID-19 pandemic."),
      # Leaflet output:
      leafletOutput("state_avg"),
      
      # Input: Slider for the Date ----
      sliderInput(inputId = "Dates",
                  label = "Date:",
                  min = as.Date("2020-03-01","%Y-%m-%d"),
                  max = as.Date("2020-12-31","%Y-%m-%d"),
                  value=as.Date("2020-03-01"),
                  timeFormat="%Y-%m-%d",
                  width = "100%"),
      
      # Output 2: Zoomable map of county level values ----
      
      h2("Population movement over time, County Level"),
      p("Zoom into desired state and toggle with the timeline."),
      # Leaflet output:
      leafletOutput("county_level")
      
      
    
  )
)

server <- function(input, output) {
  
  output$state_avg <- renderLeaflet({
    daily_state_avg <- usa_2020 %>%
      group_by(State, ds) %>%
      summarize(avg_stay_put = mean(all_day_ratio_single_tile_users)) %>%
      filter(ds == input$Dates) # where the date toggle input will be
    
    daily_state_avg
    
    state_shp <- readOGR("cb_2021_us_state_500k/cb_2021_us_state_500k.shp",
                         verbose = FALSE)
    
    # Joining the proportions to the state spatial object df
    daily_state_avg_df <- left_join(state_shp@data, daily_state_avg,
                                    by = c("STUSPS" = "State")) %>%
      replace(is.na(.), 0)
    
    state_shp@data <- daily_state_avg_df
    
    choro_pal <- colorBin("YlOrRd", domain = daily_state_avg_df$avg_stay_put,
                          bins = c(0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 0.7, 1))
    
    leaflet() %>%
      addProviderTiles("CartoDB", 
                       options = providerTileOptions(minZoom = 4)) %>%
      setView(lng = -98.35, lat = 39.5, zoom = 4) %>%
      setMaxBounds(lng1 = -66.9513812, lat1 = 49.3457868,
                   lng2 = -124.7844079, lat2 = 24.7433195) %>%
      addPolygons(data = nation_shp,
                  color = "#6e7f80", 
                  weight = 2) %>%
      addPolygons(data = state_shp,
                  weight = 1,
                  color = "#6e7f80",
                  fillColor = ~choro_pal(daily_state_avg$avg_stay_put),
                  fillOpacity = 0.5,
                  label = state_shp$NAME,
                  group = "State",
                  highlightOptions = highlightOptions(color = "black", 
                                                      weight = 3)) %>%
      addLegend(pal = choro_pal, 
                values = daily_state_avg$avg_stay_put, 
                opacity = 0.7, 
                title = "% population staying put:</br> State daily average", 
                position = "bottomright") %>%
      addLayersControl(overlayGroups = c("State", "County"))
  })
  
  output$county_level <- renderLeaflet({
    
    county_day <- usa_2020 %>%
      filter(ds == input$Dates)
    
    county_shp <- readOGR("cb_2021_us_county_500k/cb_2021_us_county_500k.shp",
                          verbose = FALSE)
    
    # Joining the proportions to the state spatial object df
    daily_county_df <- left_join(county_shp@data, county_day,
                                 by = c("NAME" = "County",
                                        "STUSPS" = "State")) %>%
      replace(is.na(.), 0)
    
    county_shp@data <- daily_county_df
    
    choro_pal <- colorBin("YlOrRd", domain = daily_county_df$all_day_ratio_single_tile_users,
                          bins = c(0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 0.7, 1))
    
    leaflet() %>%
      addProviderTiles("CartoDB", 
                       options = providerTileOptions(minZoom = 4)) %>%
      setView(lng = -98.35, lat = 39.5, zoom = 4) %>%
      setMaxBounds(lng1 = -66.9513812, lat1 = 49.3457868,
                   lng2 = -124.7844079, lat2 = 24.7433195) %>%
      addPolygons(data = nation_shp,
                  color = "#6e7f80", 
                  weight = 2) %>%
      addPolygons(data = state_shp,
                  weight = 1,
                  color = "#6e7f80",
                  label = state_shp$NAME,
                  group = "State",
                  highlightOptions = highlightOptions(color = "black", 
                                                      weight = 3)) %>%
      addPolygons(data = county_shp,
                  weight = 1,
                  color = "#6e7f80",
                  fillColor = ~choro_pal(daily_county_df$all_day_ratio_single_tile_users),
                  fillOpacity = 0.5,
                  label = county_shp$NAME,
                  group = "County",
                  highlightOptions = highlightOptions(color = "black", 
                                                      weight = 3)) %>%
      addLegend(pal = choro_pal, 
                values = daily_county_df$all_day_ratio_single_tile_users, 
                opacity = 0.7, 
                title = "% population staying put - County level", 
                position = "bottomright") %>%
      addLayersControl(overlayGroups = c("State", "County"))
  })
  
}

shinyApp(ui, server)
```

