---
title: "unemployment"
author: "Yu Wang"
date: "4/24/2022"
output: html_document
---

```{r,  echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center", warning = FALSE, message = FALSE)
```

```{r,  echo=FALSE, message=FALSE}
library(ggplot2)
library(tidyverse)
library(zoo)
library(dplyr)
library(lubridate)
library(plotly)
library(devtools)
library(leaflet)
library(readr)
library(rgdal)
library(tmap)
library(ggmap)
library(RColorBrewer)
library(htmltools)


```

```{r,  echo=FALSE, message=FALSE}
total <- read.csv("/Users/yuwang/Documents/GitHub/gr5063/Group_A_COVID-19_insights/umployment rate/SeriesReport-20220423235636_21d8c2.csv", stringsAsFactors = FALSE)
states <- read.csv("/Users/yuwang/Documents/GitHub/gr5063/Group_A_COVID-19_insights/umployment rate/unemployment by states.csv", stringsAsFactors = FALSE)
industry <- read.csv("/Users/yuwang/Documents/GitHub/gr5063/Group_A_COVID-19_insights/umployment rate/Unempolyment rate by industry.csv", stringsAsFactors = FALSE)
```

```{r,  echo=FALSE, message=FALSE}

total1 <- total %>% 
  gather("id", "value", 2:13) %>%
  filter(id == "Jun"|id == "Dec", Year >= 2016 & Year != 2022)

total1$month <- match(total1[, 2], month.abb)

total1$Date <- paste(total1$Year,total1$month)
total1$Date <- ym(total1$Date)

total1 <- total1 %>%
  arrange(Date)

total1$value1 <- paste0(as.matrix(total1$value), "%")
```



<font size="5"> <center>  **US Unemployment Rate Over Time** </center></font> 




```{r,fig.align='right',echo=FALSE, message=FALSE}
plot1 <- plot_ly(total1, x = ~Date, y = ~value1, type = 'scatter', mode = 'lines+markers', text = ~value) %>%
    layout(
         xaxis = list(showgrid = FALSE, title = "Year"),
         yaxis = list(title = "Unemployment Rate %")
      
             )  %>%
  add_text(text = ~value1, textposition = "top center",
           showlegend = F)



plot1_centered <- div(plot1, align = "center")
  
plot1_centered
```

<font size="3"> <center> This photo   </center></font> 


The second visualization of unemployment rate is shows trend of different industries
```{r,  echo=FALSE, message=FALSE}
ind <- industry%>% 
  gather("id", "value", 3:6)

ind1 = subset(ind, select = -c(3:6))

ind1$Date <- paste(ind1$Year,ind1$id)

ind1$Date <- yq(ind1$Date)


```



```{r,echo=FALSE, message=FALSE, fig.align="center"}
plot2 <- ggplot(ind1, aes(Date, value, col = Industry)) +
  geom_line()+
  facet_wrap(Industry ~., nrow = 5,scales = "free_y") +
  theme(strip.text = element_text(size = 6.5, margin = margin()))+
  labs(x="Year", y="Unemployment Rate %")

plotly2 <-ggplotly(plot2)

plot2_centered <- div(plotly2, align = "center")

plot2_centered
```




The third visualization of unemployment rate is an interactive map of US states
```{r,  echo=FALSE, message=FALSE}
colnames(states)[2] <- 'Rate_2019'
colnames(states)[3] <- 'Rate_2020'
colnames(states)[4] <- 'Rate_2021'

```

```{r,  echo=FALSE, message=FALSE}
geom <- read.csv("/Users/yuwang/Documents/GitHub/gr5063/Group_A_COVID-19_insights/umployment rate/statelatlong.csv")

colnames(geom)[4] <- 'State'

geom = subset(geom, select = -c(1))
```

```{r,  echo=FALSE, message=FALSE}
statesgeom <- states %>%
  left_join(geom, by = 'State')
```


```{r,  echo=FALSE, message=FALSE}
usstates <- 
    geojsonio::geojson_read( 
        x = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
        , what = "sp"
    )
```

```{r,  echo=FALSE, message=FALSE}
library(RColorBrewer)

pal3 = colorFactor("Set1", domain = states$State)
color_offsel3 = pal3(states$State)
```

```{r,  echo=FALSE, message=FALSE, fig.align="center"}
content3 <- paste("unemployment Rate:",statesgeom$Rate_2019,"<br/>",
                  "State:",statesgeom$State,"<br/>")

content4 <- paste("unemployment Rate:",statesgeom$Rate_2020,"<br/>",
                  "State",statesgeom$State,"<br/>")

content5 <- paste("unemployment Rate:",statesgeom$Rate_2021,"<br/>",
                  "State",statesgeom$State,"<br/>")

unemployment_map <- leaflet(data=statesgeom) %>%
  setView(-96, 37.8, 4) %>%
  addTiles(group = "OSM") %>%
  addPolygons(data=usstates,group = '2019',
              stroke = TRUE, smoothFactor = 0.5,
              weight=2,  opacity=1,
              color = 'white',
              popup = content3) %>%
  addPolygons(data=usstates,group = '2020',
              stroke = TRUE, smoothFactor = 0.5,
              weight=2,  opacity=1,
              color = 'orange',
              popup = content4) %>%
    addPolygons(data=usstates,group = '2021',
              stroke = TRUE, smoothFactor = 0.5,
              weight=2,  opacity=1,
              color = 'blue',
              popup = content5) %>%
  addLayersControl( #<<
    baseGroups = c("OpenStreetMap"), #<<
    overlayGroups = c("2019",'2020','2021'), #<<
    options = layersControlOptions(collapsed = TRUE) )

unemployment_map_centered <- div(unemployment_map, align = "center")

unemployment_map_centered
```






